/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\project\\blog-web\\blog-web-new\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-50c6eb10",
    path: "/theme-reco/plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50c6eb10").then(next)
    },
  },
  {
    name: "v-7c57fcdb",
    path: "/theme-reco/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c57fcdb").then(next)
    },
  },
  {
    path: "/theme-reco/index.html",
    redirect: "/theme-reco/"
  },
  {
    name: "v-4f57ecae",
    path: "/front-end/vue/vue_axios.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f57ecae").then(next)
    },
  },
  {
    name: "v-2d762848",
    path: "/theme-reco/axios.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d762848").then(next)
    },
  },
  {
    name: "v-117744e2",
    path: "/theme-reco/theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-117744e2").then(next)
    },
  },
  {
    name: "v-2bdd2d2f",
    path: "/front-end/vue/Vuex.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2bdd2d2f").then(next)
    },
  },
  {
    name: "v-78b69a80",
    path: "/theme-reco/api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78b69a80").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]