/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "plugin",
      "frontmatter": {
        "title": "plugin",
        "date": "2020-05-28T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/plugin.html",
      "relativePath": "theme-reco/plugin.md",
      "key": "v-50c6eb10",
      "path": "/theme-reco/plugin.html"
    },
    {
      "title": "theme-reco",
      "frontmatter": {
        "title": "theme-reco",
        "date": "2020-05-29T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/",
      "relativePath": "theme-reco/README.md",
      "key": "v-7c57fcdb",
      "path": "/theme-reco/"
    },
    {
      "title": "axios",
      "frontmatter": {
        "title": "axios",
        "date": "2021-12-02 08:00:00",
        "sidebar": "auto",
        "categories": [
          "FrontWeb"
        ],
        "tags": [
          "VUE"
        ],
        "publish": true
      },
      "regularPath": "/front-end/vue/vue_axios.html",
      "relativePath": "front-end/vue/vue_axios.md",
      "key": "v-4f57ecae",
      "path": "/front-end/vue/vue_axios.html",
      "headers": [
        {
          "level": 2,
          "title": "axios",
          "slug": "axios"
        },
        {
          "level": 3,
          "title": "一、简介",
          "slug": "一、简介"
        }
      ]
    },
    {
      "title": "axios",
      "frontmatter": {
        "title": "axios",
        "date": "2020-05-28T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/axios.html",
      "relativePath": "theme-reco/axios.md",
      "key": "v-2d762848",
      "path": "/theme-reco/axios.html"
    },
    {
      "title": "theme",
      "frontmatter": {
        "title": "theme",
        "date": "2020-05-27T00:00:00.000Z"
      },
      "regularPath": "/theme-reco/theme.html",
      "relativePath": "theme-reco/theme.md",
      "key": "v-117744e2",
      "path": "/theme-reco/theme.html"
    },
    {
      "title": "axios222",
      "frontmatter": {
        "title": "axios222",
        "date": "2021-12-02 08:00:00",
        "sidebar": "auto",
        "categories": [
          "FrontWeb"
        ],
        "tags": [
          "VUE"
        ],
        "publish": true
      },
      "regularPath": "/front-end/vue/Vuex.html",
      "relativePath": "front-end/vue/Vuex.md",
      "key": "v-2bdd2d2f",
      "path": "/front-end/vue/Vuex.html",
      "headers": [
        {
          "level": 2,
          "title": "Vuex",
          "slug": "vuex"
        },
        {
          "level": 3,
          "title": "一、定义",
          "slug": "一、定义"
        },
        {
          "level": 3,
          "title": "二、Vuex的使用",
          "slug": "二、vuex的使用"
        }
      ]
    },
    {
      "title": "模块化开发",
      "frontmatter": {
        "title": "模块化开发",
        "date": "2021-12-28T00:00:00.000Z",
        "categories": [
          "frontEnd"
        ],
        "tags": [
          "vue"
        ]
      },
      "regularPath": "/theme-reco/api.html",
      "relativePath": "theme-reco/api.md",
      "key": "v-78b69a80",
      "path": "/theme-reco/api.html",
      "headers": [
        {
          "level": 2,
          "title": "模块化开发",
          "slug": "模块化开发"
        },
        {
          "level": 3,
          "title": "一、模块化",
          "slug": "一、模块化"
        },
        {
          "level": 2,
          "title": "Promise",
          "slug": "promise"
        },
        {
          "level": 3,
          "title": "一、定义",
          "slug": "一、定义"
        },
        {
          "level": 3,
          "title": "二、Promise的使用",
          "slug": "二、promise的使用"
        }
      ]
    }
  ],
  "themeConfig": {}
}